name: .NET Build & Test All

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: |
        dotnet restore DisplayNums/DisplayNums
        dotnet restore StudentManagement/StudentManagement
        dotnet restore StudentManagementGeneric/StudentManagementGeneric
        dotnet restore SwapGeneric/SwapGeneric
        dotnet restore TestLib/TestLib

    - name: Build
      run: |
        dotnet build DisplayNums/DisplayNums --no-restore
        dotnet build StudentManagement/StudentManagement --no-restore
        dotnet build StudentManagementGeneric/StudentManagementGeneric --no-restore
        dotnet build SwapGeneric/SwapGeneric --no-restore
        dotnet build TestLib/TestLib --no-restore

    - name: Run tests
      run: dotnet test TestLib/TestLib --no-build --verbosity normal
